--初始表
CREATE TABLE USERS(
USERNAME VARCHAR2(255) NOT NULL PRIMARY KEY,
PASSWORD VARCHAR2(255) NOT NULL,
PHONE VARCHAR2(255)
);

--MySQL----------------------------------------------------------------------------

-- CREATE DATABASE IF NOT EXISTS YOUR_SCHEMA_NAME DEFAULT CHARACTER SET = utf8mb4;
-- Use YOUR_SCHEMA_NAME;

-- CREATE TABLE `USERS` (
-- `GROUP` varchar(255) NOT NULL COMMENT '用户组',
-- `USERNAME` varchar(255) NOT NULL COMMENT '用户名',
-- `PASSWORD` varchar(255) NOT NULL COMMENT '密码',
-- `PHONE` varchar(255) COMMENT '手机',
-- PRIMARY KEY (`GROUP`,`USERNAME`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';
