
spring:
  application:
    name: ${app.id}
  ## default profile
  profiles:
    active: win
  ## Jackson config
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  ## i18n message
  messages:
    basename: msg/messages
    encoding: UTF-8
  ## MVC config for web app
  mvc:
    view:
      prefix: /
      suffix: .html

## error translate
messages:
  error-code:
    basename: msg/error-code
  error-desc:
    basename: msg/error-desc
