
## Logback (get by springProperty label in logback.xml) #############################################################


log:
  pattern: '%d %X{_trace_id_:-0000000000000000000000} %-5p %t %c{40} %L: %m%n'
  path: 'E:/__Temp/tomcat/logs/'
  archive-path: '${log.path}/archive'
  level:
    console: 'ON'
    root: INFO
    sviolet: INFO


## Web Container ####################################################################################################


server:
  port: 8080
  address: 0.0.0.0
  tomcat:
    ## TODO [重要]指定tomcat的basedir, 用于临时文件, 该目录需要创建.
    basedir: E:/__Temp/tomcat/tmp
    accept-count: 200
    max-connections: 2000
    max-http-form-post-size: 10485760
    threads:
      max: 200
      min-spare: 10
#  compression:
#    enabled: true
#    mime-types: application/json,application/xml,text/html,text/xml,text/plain
#    min-response-size: 2048
